AllCops:
  DisplayCopNames: true

Lint/EndAlignment:
  AlignWith: variable

Metrics/LineLength:
  Max: 132
Metrics/MethodLength:
  Severity: warning

# Rationale: allow Weirich-style blocks
Style/BlockDelimiters:
  Enabled: false
Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Style/MultilineOperationIndentation:
  EnforcedStyle: indented
Style/IndentArray:
  EnforcedStyle: consistent
